#ifndef X3D_H_
#define X3D_H_

#include "struct.h"
#include <stddef.h>
#include <stdbool.h>

// clang-format off

TYPEDEF_PACKED_STRUCT_BEG(X3D_FRAME_HEADER)
    VAR(BU8, length)
TYPEDEF_PACKED_STRUCT_END(X3D_FRAME_HEADER)

TYPEDEF_BITFIELD_BEG(X3D_HEADER_PAIRING_PAYLOAD_COUNTERS, LU8)
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REQUEST_0,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REQUEST_1,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REQUEST_2,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REQUEST_3,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REPLY_0,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REPLY_1,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REPLY_2,
    X3D_HEADER_PAIRING_PAYLOAD_COUNTERS_REPLY_3,
TYPEDEF_BITFIELD_END(X3D_HEADER_PAIRING_PAYLOAD_COUNTERS, LU8)

TYPEDEF_PACKED_STRUCT_BEG(X3D_HEADER_PAIRING_PAYLOAD)
    VAR(LU8, const_85)
    VAR(LU8, const_98)
    VAR(LU8, const_00)
TYPEDEF_PACKED_STRUCT_END(X3D_HEADER_PAIRING_PAYLOAD)

TYPEDEF_ENUM_BEG(X3D_PAIRING_PAYLOAD_STATUS)
    X3D_PAIRING_PAYLOAD_STATUS_Open = 0xe0,
    X3D_PAIRING_PAYLOAD_STATUS_Pinned = 0xe5,
TYPEDEF_ENUM_END(X3D_PAIRING_PAYLOAD_STATUS)

TYPEDEF_PACKED_STRUCT_BEG(X3D_PAIRING_PAYLOAD)
    BITFIELD_VAR(X3D_HEADER_PAIRING_PAYLOAD_COUNTERS, counters)
    VAR(LU16, transfer_slot)
    VAR(LU16, transfered_slot)
    VAR(LU8, const_1f)
    VAR(LU8, const_ff)
    VAR(LU8, slot)
    VAR(LU8, const_00)
    VAR(LU16, rnd)
    ENUM_VAR(X3D_PAIRING_PAYLOAD_STATUS, status)
TYPEDEF_PACKED_STRUCT_END(X3D_PAIRING_PAYLOAD)

TYPEDEF_PACKED_STRUCT_BEG(X3D_HEADER_BEACON_PAYLOAD)
    VAR(LU8, const_05)
    VAR(LU8, const_98)
    VAR(LU8, const_00)
TYPEDEF_PACKED_STRUCT_END(X3D_HEADER_BEACON_PAYLOAD)

TYPEDEF_ENUM_BEG(X3D_MESSAGE_TYPE)
    X3D_MESSAGE_TYPE_Sensor = 0,
    X3D_MESSAGE_TYPE_Standard = 1,
    X3D_MESSAGE_TYPE_Pairing = 2,
    X3D_MESSAGE_TYPE_Beacon = 3,
TYPEDEF_ENUM_END(X3D_MESSAGE_TYPE)

TYPEDEF_BITFIELD_BEG(X3D_CONTROL, LU8)
    X3D_CONTROL_HEADER_LENGTH_0,
    X3D_CONTROL_HEADER_LENGTH_1,
    X3D_CONTROL_HEADER_LENGTH_2,
    X3D_CONTROL_HEADER_LENGTH_3,
    X3D_CONTROL_HEADER_LENGTH_4,
    X3D_CONTROL_HEADER_F5,
    X3D_CONTROL_HEADER_F6,
    X3D_CONTROL_HEADER_F7,
TYPEDEF_BITFIELD_END(X3D_CONTROL, LU8)

TYPEDEF_PACKED_STRUCT_BEG(X3D_BODY_START)
    VAR(LU8, const_ff)
    VAR(LU8, seq)
    ENUM_VAR(X3D_MESSAGE_TYPE, type)
    BITFIELD_VAR(X3D_CONTROL, control)
TYPEDEF_PACKED_STRUCT_END(X3D_BODY_START)

TYPEDEF_PACKED_STRUCT_BEG(X3D_HEADER_START)
    VAR(LU24, device_id)
    VAR(LU8, network_id)
TYPEDEF_PACKED_STRUCT_END(X3D_HEADER_START)

TYPEDEF_PACKED_STRUCT_BEG(X3D_HEADER_END)
    VAR(LU16, msg_id)
TYPEDEF_PACKED_STRUCT_END(X3D_HEADER_END)

TYPEDEF_PACKED_STRUCT_BEG(X3D_HEADER_FOOTER)
    VAR(BU16, checksum)
TYPEDEF_PACKED_STRUCT_END(X3D_HEADER_FOOTER)

TYPEDEF_PACKED_STRUCT_BEG(X3D_FRAME_FOOTER)
    VAR(BU16, checksum)
TYPEDEF_PACKED_STRUCT_END(X3D_FRAME_FOOTER)

// clang-format on
#ifdef __cplusplus
                                                                                    extern "C"
{
#endif
    void x3d_print(uint8_t *data, size_t size);
    void x3d_body_print(uint8_t *data, size_t size);
    size_t x3d_get_frame_size(uint8_t *data, size_t size);
    uint16_t x3d_compute_checksum(uint8_t *data, size_t size);
    uint16_t x3d_enc_msg_id(uint16_t msgId, uint32_t deviceId);
    uint16_t x3d_dec_msg_id(uint16_t encMsgId, uint32_t deviceId);
    uint16_t x3d_compute_header_checksum(uint8_t *data, size_t size);
#ifdef __cplusplus
}
#endif

#endif